# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Zheyuan
title: UCSC CSE graduate student
email: sephirotheca17@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  ArberSephirotheca
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: ZheyuanChen
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/2406919-_asuka_subs_neon_genesis_evangelion_remastered_08___asuka_strikes__dvd_704x480_x264_aac_ogg_.mkv_snapshot_21.51__2013.01.03_08.30.09_.png
about_content: | # this will include new lines to allow paragraphs
  Hi, My name is Zheyuan Chen

  Skill Set: Rust, Go, C/C++, Python

content:
  - title: Projects/Open Source Contribution # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Telescope
        link: https://github.com/rcos/Telescope
      - layout: top-middle
        title: Opendal
        link: https://github.com/datafuselabs/opendal
      - layout: top-middle
        title: curveadm
        link: https://github.com/opencurve/curveadm
        
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rensselaer Center for Open Source
        link: https://rcos.io
        # link_text: boringcompany.com
        sub_title: On campus Software Engineering Intern
        caption: Dec 2021 - April 2022
        description: Our Mission is to cultivate an inclusive, creative, and entrepreneurial community that seeks to empower students to develop open-source solutions to real-world problems. Help the RCOS to develop a website using actix-web framework in Rust.
    
      - layout: left
        title: Open Source Promotion Plan
        link: https://summer-ospp.ac.cn
        # link_text: boringcompany.com
        sub_title: Open Source Promotion Plan 2022 participant with NetEase
        caption: June 2022 - September 2022
        description: Help the company [Netease](http://www.neteasegames.com) to develop a cluster management system in Go called Curveadm. CurveAdm is a tool for deploy and manage Curve cluster, it's easy to use and with rich features.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  University of California, Santa Cruz
        caption: 2022 - Present
        sub_title: MS CSE

      - layout: left
        title:  Rensselaer Polytechnic Insititute
        caption: 2018 - 2022
        sub_title: BS Computer Science

  - title: Research Interest
    layout: text
    content: |
      - Distributed System
      - Compiler
      - Operating System
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer science some of my other interests and hobbies are:
      - Gaming
      - Traveling 


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
